services:
  - type: web
    name: mock-interview
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "8080"
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: FRONTEND_ORIGIN
        value: https://mock-interviews-chi.vercel.app
