services:
  - type: web
    name: mock-interview-api
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /api/v1/marketplace/technologies
    envVars:
      - key: PORT
        value: "8080"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FRONTEND_ORIGIN
        value: https://mock-interviews1.vercel.app
      - key: DB_SCHEMA
        value: interviewhub
